#!/usr/bin/env python3
"""
Plot cell survival curves from PIDE CSV data files
Generated by test_pide_reader
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os

# Set the working directory to where the CSV files are
script_dir = os.path.dirname(os.path.abspath(__file__))

# Check if running from build directory
if os.path.exists('pide_v79_12C_rawdata.csv'):
    data_dir = '.'
elif os.path.exists(os.path.join(script_dir, '../RAD-build/PIDEDataReader/pide_v79_12C_rawdata.csv')):
    data_dir = os.path.join(script_dir, '../RAD-build/PIDEDataReader')
else:
    data_dir = '.'

print(f"Reading data from: {data_dir}")

# Load the CSV files
raw_data = pd.read_csv(os.path.join(data_dir, 'pide_v79_12C_rawdata.csv'))
lq_params = pd.read_csv(os.path.join(data_dir, 'pide_v79_LQ_parameters.csv'))
sf_curves = pd.read_csv(os.path.join(data_dir, 'pide_v79_survival_curves.csv'))

print(f"Loaded {len(raw_data)} raw data points")
print(f"Loaded {len(lq_params)} LQ parameter entries")
print(f"Loaded {len(sf_curves)} survival curve points")

# Create figure with 2x2 subplots
fig, axes = plt.subplots(2, 2, figsize=(14, 12))

# ========================================
# Plot 1: Raw experimental data (V79 + 12C)
# ========================================
ax1 = axes[0, 0]

# Get unique experiments
exp_ids = raw_data['ExpID'].unique()
colors = plt.cm.viridis(np.linspace(0, 0.9, min(8, len(exp_ids))))

for i, exp_id in enumerate(exp_ids[:8]):
    exp_data = raw_data[raw_data['ExpID'] == exp_id]
    let = exp_data['LET_keV_um'].iloc[0]
    ax1.semilogy(exp_data['Dose_Gy'], exp_data['SurvivalFraction'], 
                'o-', color=colors[i], markersize=6, linewidth=1.5,
                label=f'LET={let:.1f} keV/μm')

ax1.set_xlabel('Dose (Gy)', fontsize=12)
ax1.set_ylabel('Survival Fraction', fontsize=12)
ax1.set_title('V79 + 12C: Raw Experimental Data\n(from PIDE database)', fontsize=14)
ax1.legend(loc='lower left', fontsize=9)
ax1.set_xlim(0, 10)
ax1.set_ylim(1e-4, 1.5)
ax1.grid(True, alpha=0.3)

# ========================================
# Plot 2: LQ model survival curves (different ions)
# ========================================
ax2 = axes[0, 1]

ion_colors = {'4He': 'blue', '12C': 'green', '20Ne': 'orange', '56Fe': 'red'}

for ion in sf_curves['Ion'].unique():
    ion_data = sf_curves[sf_curves['Ion'] == ion]
    let = ion_data['LET_keV_um'].iloc[0]
    color = ion_colors.get(ion, 'gray')
    ax2.semilogy(ion_data['Dose_Gy'], ion_data['SurvivalFraction'], 
                '-', color=color, linewidth=2,
                label=f'{ion} (LET={let:.1f} keV/μm)')

ax2.set_xlabel('Dose (Gy)', fontsize=12)
ax2.set_ylabel('Survival Fraction', fontsize=12)
ax2.set_title('V79 Cell Survival: Different Ion Types\n(LQ model from PIDE)', fontsize=14)
ax2.legend(loc='lower left', fontsize=10)
ax2.set_xlim(0, 10)
ax2.set_ylim(1e-4, 1.5)
ax2.grid(True, alpha=0.3)

# ========================================
# Plot 3: Alpha vs LET
# ========================================
ax3 = axes[1, 0]

# Filter valid alpha values
lq_valid = lq_params[lq_params['alpha_paper'] != 'NA'].copy()
lq_valid['alpha_paper'] = pd.to_numeric(lq_valid['alpha_paper'])
lq_valid['LET_keV_um'] = pd.to_numeric(lq_valid['LET_keV_um'])

# Group by ion
ion_markers = {'4He': 'o', '12C': 's', '20Ne': '^', '56Fe': 'd', '1H': 'v'}
ion_colors_scatter = {'4He': 'blue', '12C': 'green', '20Ne': 'orange', '56Fe': 'red', '1H': 'purple'}

for ion in lq_valid['Ion'].unique():
    ion_data = lq_valid[lq_valid['Ion'] == ion]
    if len(ion_data) > 0:
        marker = ion_markers.get(ion, 'o')
        color = ion_colors_scatter.get(ion, 'gray')
        ax3.scatter(ion_data['LET_keV_um'], ion_data['alpha_paper'], 
                   marker=marker, s=50, color=color, alpha=0.7, label=ion)

ax3.set_xlabel('LET (keV/μm)', fontsize=12)
ax3.set_ylabel('α (Gy⁻¹)', fontsize=12)
ax3.set_title('V79: Radiosensitivity vs LET\n(α parameter from LQ model)', fontsize=14)
ax3.legend(loc='upper left', fontsize=10)
ax3.set_xscale('log')
ax3.set_xlim(1, 1000)
ax3.grid(True, alpha=0.3)

# ========================================
# Plot 4: Detailed V79 + 12C with LET groups
# ========================================
ax4 = axes[1, 1]

# Group by LET ranges
let_ranges = [(0, 20), (20, 50), (50, 100), (100, 500)]
let_colors = ['blue', 'green', 'orange', 'red']
let_labels = ['LET < 20', '20-50', '50-100', '> 100 keV/μm']

for (let_min, let_max), color, label in zip(let_ranges, let_colors, let_labels):
    let_data = raw_data[(raw_data['LET_keV_um'] >= let_min) & (raw_data['LET_keV_um'] < let_max)]
    if len(let_data) > 0:
        ax4.semilogy(let_data['Dose_Gy'], let_data['SurvivalFraction'], 
                    'o', color=color, markersize=5, alpha=0.6, label=label)

ax4.set_xlabel('Dose (Gy)', fontsize=12)
ax4.set_ylabel('Survival Fraction', fontsize=12)
ax4.set_title('V79 + 12C: Grouped by LET Range\n(raw data)', fontsize=14)
ax4.legend(loc='lower left', fontsize=10)
ax4.set_xlim(0, 10)
ax4.set_ylim(1e-4, 1.5)
ax4.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig(os.path.join(data_dir, 'pide_survival_curves.png'), dpi=150, bbox_inches='tight')
plt.savefig(os.path.join(data_dir, 'pide_survival_curves.pdf'), bbox_inches='tight')
print(f"Saved: {os.path.join(data_dir, 'pide_survival_curves.png')}")

# ========================================
# Create a single detailed plot
# ========================================
fig2, ax = plt.subplots(figsize=(10, 8))

# Plot raw data grouped by LET
for (let_min, let_max), color, label in zip(let_ranges, let_colors, let_labels):
    let_data = raw_data[(raw_data['LET_keV_um'] >= let_min) & (raw_data['LET_keV_um'] < let_max)]
    if len(let_data) > 0:
        ax.semilogy(let_data['Dose_Gy'], let_data['SurvivalFraction'], 
                   'o', color=color, markersize=8, alpha=0.7, label=f'{label} (n={len(let_data)})')

ax.set_xlabel('Dose (Gy)', fontsize=14)
ax.set_ylabel('Survival Fraction', fontsize=14)
ax.set_title('V79 Cell Survival with 12C Ions\nRaw Data from PIDE Database', fontsize=16)
ax.legend(loc='lower left', fontsize=11)
ax.set_xlim(0, 10)
ax.set_ylim(1e-4, 1.5)
ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig(os.path.join(data_dir, 'pide_v79_12C_survival.png'), dpi=150, bbox_inches='tight')
print(f"Saved: {os.path.join(data_dir, 'pide_v79_12C_survival.png')}")

print("\nDone! Survival curve plots generated from CSV data.")
